server: 
  port: 9001
  servlet:
    context-path: /

#elastic-job zk设置
elaticjob : 
  zookeeper:
    server-lists: 10.0.13.11:5181,10.0.13.11:5182,10.0.13.11:5183
    namespace: demo_job
    sessiontimeout: 30000
#elastic-job 任务设置
elastic: 
  job: 
    demoSimpleJob: 
      jobName: demoSimpleJob
      cron: 0 0 1 1 1/1 ? 
      shardingTotalCount: 1
      shardingItemParameters: 0=0
      failover: true
    demoDataFlowJob: 
      jobName: demoDataflow
      cron: 0 0 1 1 1/1 ? 
      shardingTotalCount: 3
      shardingItemParameters: 0=A,1=B,2=C
      failover: true

    


  
 
    
  